---
sidebar: sidebar 
permalink: faq-cloud-tiering.html 
keywords: faq, questions, requirements, service connector, agent, object store, object storage, aws, azure, bucket, cluster, aggregate, s3, storage class, standard, inactive data reporting, auto, volume tiering policy, policy, tiering policy, snapshot, cold, inactive, infrequent, agent, netapp console, console,cloud tier 
summary: Cette FAQ peut vous aider si vous cherchez simplement une réponse rapide à une question. 
---
= FAQ technique sur la NetApp Cloud Tiering
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cette FAQ peut vous aider si vous recherchez simplement une réponse rapide à une question concernant NetApp Cloud Tiering.



== Service de hiérarchisation du cloud

Les questions fréquentes suivantes expliquent le fonctionnement du Cloud Tiering.



=== Quels sont les avantages de l'utilisation du service Cloud Tiering ?

Le Cloud Tiering répond aux défis liés à la croissance rapide des données, en vous offrant des avantages tels que :

* Extension facile des centres de données vers le cloud, offrant jusqu'à 50 fois plus d'espace.
* Optimisation du stockage, permettant une économie de stockage moyenne de 70 %
* Coût total de possession réduit de 30 % en moyenne
* Pas besoin de remanier les applications




=== Quels types de données sont utiles à transférer vers le cloud ?

En résumé, toutes les données considérées comme inactives sur les systèmes de stockage primaires et secondaires constituent une cible idéale pour être transférées vers le cloud.  Sur les systèmes principaux, ces données peuvent inclure des instantanés, des enregistrements historiques et des projets terminés.  Sur les systèmes secondaires, cela inclut tous les volumes contenant des copies des données primaires réalisées à des fins de reprise après sinistre et de sauvegarde.



=== Est-il possible de hiérarchiser les données provenant à la fois de volumes NAS et de volumes SAN ?

Oui, vous pouvez hiérarchiser les données des volumes NAS vers le cloud public ou vers des clouds privés, comme StorageGRID.  Lors de la hiérarchisation des données accessibles via les protocoles SAN, NetApp recommande l'utilisation de clouds privés, car les protocoles SAN sont plus sensibles aux problèmes de connectivité que les NAS.



=== Quelle est la définition des données inactives ou des données rarement utilisées, et comment sont-elles contrôlées ?

La définition de ce que l'on peut également appeler données froides est la suivante : « blocs de volume (métadonnées exclues) qui n'ont pas été consultés depuis un certain temps ».  La « durée » est déterminée par un attribut de politique de hiérarchisation appelé « jours de refroidissement ».



=== La hiérarchisation du stockage dans le cloud me permettra-t-elle de conserver mes gains d'efficacité en matière de stockage dans le niveau cloud ?

Oui, les gains d'efficacité du stockage au niveau volume ONTAP , tels que la compression, la déduplication et le compactage, sont préservés lors du déplacement des données vers le cloud.



=== Quelle est la différence entre FabricPool et Cloud Tiering ?

FabricPool est la technologie de hiérarchisation ONTAP qui peut être gérée automatiquement via l'interface de ligne de commande ONTAP et System Manager, ou gérée en tant que service via Cloud Tiering.  Cloud Tiering transforme FabricPool en un service géré doté de processus d'automatisation avancés, à la fois sur ONTAP et dans le cloud, offrant une meilleure visibilité et un meilleur contrôle sur la hiérarchisation dans les déploiements hybrides et multicloud.



=== Les données stockées dans le cloud peuvent-elles être utilisées pour la reprise après sinistre ou pour la sauvegarde/l'archivage ?

Non. Étant donné que les métadonnées du volume ne sont jamais séparées du niveau de performance, les données stockées dans le stockage objet ne sont pas accessibles directement.

Cependant, la hiérarchisation du cloud peut être utilisée pour réaliser une sauvegarde et une reprise après sinistre rentables en l'activant sur les systèmes secondaires et les volumes de destination SnapMirror (volumes DP), afin de hiérarchiser toutes les données (métadonnées exclues), réduisant ainsi l'empreinte de votre centre de données et le coût total de possession.



=== Le Cloud Tiering est-il appliqué au niveau du volume ou au niveau agrégé ?

La hiérarchisation du cloud est activée au niveau du volume en associant une stratégie de hiérarchisation à chaque volume.  L'identification des données froides s'effectue au niveau des blocs.



=== Comment le Cloud Tiering détermine-t-il quels blocs déplacer vers le cloud ?

La politique de hiérarchisation associée au volume est le mécanisme qui contrôle quels blocs sont hiérarchisés et à quel moment.  La politique définit le type de blocs de données (instantanés, données utilisateur ou les deux) et la période de refroidissement. Voirlink:concept-cloud-tiering.html#volume-tiering-policies["Politiques de hiérarchisation des volumes"] pour plus de détails.



=== Comment le Cloud Tiering affecte-t-il la capacité de volume ?

Le Cloud Tiering n'a aucun effet sur la capacité du volume, mais plutôt sur l'utilisation du niveau de performance agrégé.



=== La hiérarchisation du cloud permet-elle de générer des rapports sur les données inactives ?

Oui, la hiérarchisation du cloud active la génération de rapports de données inactives (IDR) sur chaque agrégat.  Ce paramètre nous permet d'identifier la quantité de données inactives pouvant être transférées vers un stockage objet à faible coût.



=== Combien de temps faut-il à IDR pour afficher les informations à partir du moment où je le lance ?

L'affichage des informations sur l'IDR commence une fois la période de refroidissement configurée écoulée.  Avec ONTAP 9.7 et les versions antérieures, IDR disposait d'une période de refroidissement non réglable de 31 jours.  À partir d' ONTAP 9.8, la période de refroidissement IDR peut être configurée jusqu'à 183 jours.



== Licences et coûts

Les questions fréquentes suivantes concernent les licences et les coûts d'utilisation du Cloud Tiering.



=== Combien coûte l'utilisation du Cloud Tiering ?

Lors du transfert de données froides vers le cloud public :

* Pour l'abonnement à la carte (PAYGO), basé sur l'utilisation : 0,05 $ par Go/mois.
* Pour l'abonnement annuel (BYOL), à durée déterminée : à partir de 0,033 $ par Go/mois.


https://bluexp.netapp.com/pricing["Voir les détails des prix"].

Le transfert de données froides vers un système NetApp StorageGRID (cloud privé) est gratuit.



=== Puis-je avoir à la fois une licence BYOL et une licence PAYGO pour le même cluster ONTAP ?

Oui. Le Cloud Tiering vous permet d'utiliser une licence BYOL, un abonnement PAYGO ou une combinaison des deux.



=== Que se passe-t-il si j'ai atteint la limite de capacité BYOL ou si ma licence BYOL expire ?

Si vous atteignez la limite de capacité BYOL ou si votre licence BYOL expire, la hiérarchisation des nouvelles données froides s'arrête.  Toutes les données précédemment hiérarchisées restent accessibles ; ce qui signifie que vous pouvez récupérer et utiliser ces données.  Une fois récupérées, ces données sont transférées du cloud vers le niveau de performance.

Toutefois, si vous disposez d'un abonnement PAYGO au service _BlueXP - Déploiement et gestion des services de données cloud_, les nouvelles données froides continueront d'être stockées dans des objets et vous paierez ces frais à l'utilisation.



=== La licence Cloud Tiering inclut-elle les frais de sortie du fournisseur de cloud ?

Non, ce n'est pas le cas.



=== La réhydratation d'un système sur site est-elle soumise aux frais de sortie facturés par les fournisseurs de cloud ?

Oui. Toutes les lectures depuis le cloud public sont soumises à des frais de sortie.



=== Comment puis-je estimer mes frais de cloud ?  Existe-t-il un mode « et si » pour le Cloud Tiering ?

Le meilleur moyen d'estimer le coût de l'hébergement de vos données chez un fournisseur de services cloud est d'utiliser ses calculateurs : https://calculator.aws/#/["AWS"] , https://azure.microsoft.com/en-us/pricing/calculator/["Azuré"] et https://cloud.google.com/products/calculator["Google Cloud"] .



=== Les fournisseurs de services cloud facturent-ils des frais supplémentaires pour la lecture/récupération de données du stockage objet vers le stockage sur site ?

Oui. Vérifier https://aws.amazon.com/s3/pricing/["Tarification d'Amazon S3"] , https://azure.microsoft.com/en-us/pricing/details/storage/blobs/["Tarification des blocs"] , et https://cloud.google.com/storage/pricing["Tarification du stockage cloud"] pour les frais supplémentaires occasionnés par la lecture/récupération des données.



=== Comment puis-je estimer les économies réalisées sur mes volumes et obtenir un rapport de données à froid avant d'activer le Cloud Tiering ?

Pour obtenir une estimation, ajoutez votre cluster ONTAP à la NetApp Console et examinez-le via la page Cloud Tiering Clusters. Sélectionnez *Calculer les économies potentielles liées à la hiérarchisation* pour que le cluster lance le https://www.netapp.com/data-services/tiering/tco-calculator["Calculateur de coût total de possession (TCO) pour la hiérarchisation du cloud"^] pour voir combien d'argent vous pouvez économiser.



=== Comment sont facturés les services à plusieurs niveaux lorsque j'utilise un ONTAP MetroCluster?

Lorsqu'elle est utilisée dans des environnements MetroCluster , la licence de hiérarchisation totale s'applique à l'utilisation des deux clusters.  Par exemple, si vous disposez d'une licence pour 100 Tio de hiérarchisation, la capacité de hiérarchisation utilisée par chaque cluster contribue à la capacité totale de 100 Tio.



== ONTAP

Les questions suivantes concernent ONTAP.



=== Quelles versions ONTAP sont prises en charge par Cloud Tiering ?

Cloud Tiering prend en charge la version ONTAP 9.2 et supérieures.



=== Quels types de systèmes ONTAP sont pris en charge ?

La hiérarchisation du cloud est prise en charge avec les clusters AFF, FAS et ONTAP Select à nœud unique et à haute disponibilité.  Les clusters dans les configurations FabricPool Mirror et MetroCluster sont également pris en charge.



=== Est-il possible de hiérarchiser les données provenant de systèmes FAS contenant uniquement des disques durs ?

Oui, à partir d' ONTAP 9.8, vous pouvez hiérarchiser les données provenant de volumes hébergés sur des agrégats de disques durs.



=== Est-il possible de hiérarchiser les données d'un AFF joint à un cluster comportant des nœuds FAS avec disques durs ?

Oui. La hiérarchisation du cloud peut être configurée pour hiérarchiser les volumes hébergés sur n'importe quel agrégat.  La configuration de hiérarchisation des données est indépendante du type de contrôleur utilisé et du caractère hétérogène ou non du cluster.



=== Qu'en est-il de Cloud Volumes ONTAP?

Si vous disposez de systèmes Cloud Volumes ONTAP , vous les trouverez sur la page Clusters de hiérarchisation cloud, ce qui vous permettra d'avoir une vue complète de la hiérarchisation des données dans votre infrastructure cloud hybride.  Cependant, les systèmes Cloud Volumes ONTAP sont en lecture seule depuis Cloud Tiering.  Il est impossible de configurer la hiérarchisation des données sur Cloud Volumes ONTAP depuis Cloud Tiering. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-tiering.html["Vous configurez la hiérarchisation des systèmes Cloud Volumes ONTAP depuis le système ONTAP dans la NetApp Console."^] .



=== Quelles sont les autres exigences nécessaires pour mes clusters ONTAP ?

Cela dépend de la façon dont vous hiérarchisez les données froides.  Pour plus de détails, veuillez consulter les liens suivants :

* link:task-tiering-onprem-aws.html#preparing-your-ontap-clusters["Hiérarchisation des données vers Amazon S3"]
* link:task-tiering-onprem-azure.html#preparing-your-ontap-clusters["Hiérarchisation des données vers le stockage Blob Azure"]
* link:task-tiering-onprem-gcp.html#preparing-your-ontap-clusters["Stockage hiérarchisé des données vers Google Cloud Storage"]
* link:task-tiering-onprem-storagegrid.html#preparing-your-ontap-clusters["Hiérarchisation des données vers StorageGRID"]
* link:task-tiering-onprem-s3-compat.html#preparing-your-ontap-clusters["Hiérarchisation des données vers le stockage d'objets S3"]




== Stockage d'objets

Les questions suivantes concernent le stockage d'objets.



=== Quels fournisseurs de stockage d'objets sont pris en charge ?

Cloud Tiering prend en charge les fournisseurs de stockage d'objets suivants :

* Amazon S3
* Blob Microsoft Azure
* Stockage Google Cloud
* NetApp StorageGRID
* Stockage d'objets compatible S3 (par exemple, MinIO)
* IBM Cloud Object Storage (la configuration FabricPool doit être effectuée à l'aide de System Manager ou de l'interface de ligne de commande ONTAP )




=== Puis-je utiliser mon propre seau/récipient ?

Oui, tu peux. Lors de la configuration de la hiérarchisation des données, vous avez la possibilité d'ajouter un nouveau compartiment/conteneur ou de sélectionner un compartiment/conteneur existant.



=== Quelles régions sont prises en charge ?

* link:reference-aws-support.html["Régions AWS prises en charge"]
* link:reference-azure-support.html["Régions Azure prises en charge"]
* link:reference-google-support.html["Régions Google Cloud prises en charge"]




=== Quelles classes de stockage S3 sont prises en charge ?

Cloud Tiering prend en charge la hiérarchisation des données vers les classes de stockage _Standard_, _Standard-Infrequent Access_, _One Zone-Infrequent Access_, _Intelligent Tiering_ et _Glacier Instant Retrieval_.  Voirlink:reference-aws-support.html["Classes de stockage S3 prises en charge"] pour plus de détails.



=== Pourquoi Amazon S3 Glacier Flexible et S3 Glacier Deep Archive ne sont-ils pas pris en charge par la hiérarchisation cloud ?

La principale raison pour laquelle Amazon S3 Glacier Flexible et S3 Glacier Deep Archive ne sont pas pris en charge est que Cloud Tiering est conçu comme une solution de hiérarchisation haute performance, les données doivent donc être disponibles en permanence et rapidement accessibles pour récupération.  Avec S3 Glacier Flexible et S3 Glacier Deep Archive, la récupération des données peut durer de quelques minutes à 48 heures.



=== Puis-je utiliser d'autres services de stockage d'objets compatibles S3, tels que MinIO, avec Cloud Tiering ?

Oui, la configuration du stockage d'objets compatible S3 via l'interface utilisateur de hiérarchisation est prise en charge pour les clusters utilisant ONTAP 9.8 et versions ultérieures. link:task-tiering-onprem-s3-compat.html["Voir les détails ici"].



=== Quels niveaux d'accès à Azure Blob sont pris en charge ?

Cloud Tiering prend en charge la hiérarchisation des données vers les niveaux d'accès _chaud_ ou _froid_ pour vos données inactives.  Voirlink:reference-azure-support.html["Niveaux d'accès Azure Blob pris en charge"] pour plus de détails.



=== Quelles classes de stockage sont prises en charge par Google Cloud Storage ?

Cloud Tiering prend en charge la hiérarchisation des données vers les classes de stockage _Standard_, _Nearline_, _Coldline_ et _Archive_.  Voirlink:reference-google-support.html["Classes de stockage Google Cloud prises en charge"] pour plus de détails.



=== La hiérarchisation du cloud prend-elle en charge l'utilisation de politiques de gestion du cycle de vie ?

Oui. Vous pouvez activer la gestion du cycle de vie afin que Cloud Tiering fasse passer les données de la classe de stockage/niveau d'accès par défaut vers un niveau plus économique après un certain nombre de jours.  La règle de cycle de vie est appliquée à tous les objets du compartiment sélectionné pour Amazon S3 et Google Cloud Storage, et à tous les conteneurs du compte de stockage sélectionné pour Azure Blob.



=== Le Cloud Tiering utilise-t-il un seul espace de stockage d'objets pour l'ensemble du cluster ou un par agrégat ?

Dans une configuration typique, il existe un seul magasin d'objets pour l'ensemble du cluster.  À partir d'août 2022, vous pourrez utiliser la page *Configuration avancée* pour ajouter des magasins d'objets supplémentaires à un cluster, puis attacher différents magasins d'objets à différents agrégats, ou attacher 2 magasins d'objets à un agrégat pour la mise en miroir.



=== Est-il possible de rattacher plusieurs seaux au même agrégat ?

Il est possible d'associer jusqu'à deux compartiments par agrégat à des fins de mise en miroir, les données froides étant réparties de manière synchrone entre les deux compartiments.  Les seaux peuvent provenir de différents fournisseurs et de différents endroits.  À partir d'août 2022, vous pourrez utiliser la page *Configuration avancée* pour connecter deux magasins d'objets à un seul agrégat.



=== Est-il possible d'associer différents compartiments à différents agrégats au sein d'un même cluster ?

Oui. La meilleure pratique générale consiste à fixer un seul godet à plusieurs agrégats.  Cependant, lors de l'utilisation du cloud public, il existe une limitation maximale d'IOPS pour les services de stockage d'objets ; il convient donc d'envisager l'utilisation de plusieurs compartiments.



=== Que se passe-t-il avec les données hiérarchisées lorsque vous migrez un volume d'un cluster à un autre ?

Lors de la migration d'un volume d'un cluster à un autre, toutes les données froides sont lues depuis le niveau cloud.  L'emplacement d'écriture sur le cluster de destination dépend de l'activation ou non de la hiérarchisation et du type de stratégie de hiérarchisation utilisée sur les volumes source et de destination.



=== Que se passe-t-il avec les données hiérarchisées lorsque vous déplacez un volume d'un nœud à un autre au sein du même cluster ?

Si l'agrégat de destination ne possède pas de couche cloud associée, les données sont lues à partir de la couche cloud de l'agrégat source et écrites intégralement sur la couche locale de l'agrégat de destination.  Si l'agrégat de destination possède un niveau cloud attaché, les données sont lues à partir du niveau cloud de l'agrégat source et écrites d'abord sur le niveau local de l'agrégat de destination, afin de faciliter une bascule rapide.  Ensuite, en fonction de la politique de hiérarchisation utilisée, il est écrit sur le niveau cloud.

À partir d' ONTAP 9.6, si l'agrégat de destination utilise le même niveau cloud que l'agrégat source, les données froides ne sont pas déplacées vers le niveau local.



=== Comment puis-je ramener mes données hiérarchisées sur site vers le niveau de performance ?

L'écriture différée est généralement effectuée sur les lectures et dépend du type de politique de hiérarchisation.  Avant ONTAP 9.8, l'écriture de l'intégralité du volume pouvait être effectuée avec une opération de _déplacement de volume_.  À partir d' ONTAP 9.8, l'interface utilisateur de hiérarchisation propose des options pour *Rétablir toutes les données* ou *Rétablir le système de fichiers actif*. link:task-managing-tiering.html#migrating-data-from-the-cloud-tier-back-to-the-performance-tier["Découvrez comment transférer les données vers le niveau de performance"].



=== Lors du remplacement d'un contrôleur AFF/ FAS existant par un nouveau, les données hiérarchisées seraient-elles migrées vers l'environnement sur site ?

Non. Lors de la procédure de « remplacement de groupe électrogène », la seule chose qui change est la propriété du groupe.  Dans ce cas, il sera remplacé par le nouveau contrôleur sans aucun transfert de données.



=== Puis-je utiliser la console du fournisseur de cloud ou les explorateurs de stockage d'objets pour consulter les données hiérarchisées dans un compartiment ?  Puis-je utiliser directement les données stockées dans le stockage d'objets sans passer par ONTAP?

Non. Les objets construits et hiérarchisés vers le cloud ne contiennent pas un seul fichier, mais jusqu'à 1 024 blocs de 4 Ko provenant de plusieurs fichiers.  Les métadonnées d'un volume restent toujours sur le niveau local.



== Agents de console

Les questions suivantes concernent l’agent de console.



=== Qu'est-ce que l'agent Console ?

L'agent de console est un logiciel exécuté sur une instance de calcul au sein de votre compte cloud ou sur site, qui permet à la NetApp Console de gérer en toute sécurité les ressources cloud. Pour utiliser le service Cloud Tiering, vous devez déployer un agent.



=== Où l’agent de console doit-il être installé ?

* Lorsque vous transférez des données vers S3, l'agent peut résider dans un VPC AWS ou sur vos locaux.
* Lorsque vous hiérarchisez les données vers le stockage Blob, l'agent peut résider dans un réseau virtuel Azure ou sur vos locaux.
* Lorsque vous transférez des données vers Google Cloud Storage, l'agent doit résider dans un VPC Google Cloud Platform.
* Lorsque vous transférez des données vers StorageGRID ou d'autres fournisseurs de stockage compatibles S3, l'agent doit résider sur vos locaux.




=== Puis-je déployer l'agent Console sur site ?

Oui. Le logiciel agent peut être téléchargé et installé manuellement sur un hôte Linux de votre réseau. https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-on-prem.html["Découvrez comment installer l'agent dans vos locaux."] .



=== Un compte auprès d'un fournisseur de services cloud est-il nécessaire avant d'utiliser la hiérarchisation cloud ?

Oui. Vous devez posséder un compte avant de pouvoir définir le stockage d'objets que vous souhaitez utiliser.  Un compte auprès d'un fournisseur de stockage cloud est également requis lors de la configuration de l'agent dans le cloud sur un VPC ou un VNet.



=== Quelles sont les conséquences d'une défaillance de l'agent Console ?

En cas de défaillance d'un agent, seule la visibilité sur les environnements hiérarchisés est affectée.  Toutes les données sont accessibles et les nouvelles données froides identifiées sont automatiquement transférées vers un stockage objet.



== Politiques de hiérarchisation



=== Quelles sont les politiques de hiérarchisation disponibles ?

Il existe quatre politiques de hiérarchisation :

* Aucun : classe toutes les données comme toujours actives ; empêche le déplacement de données du volume vers le stockage objet.
* Instantanés à froid (instantanés uniquement) : seuls les blocs d’instantanés à froid sont déplacés vers le stockage d’objets.
* Données utilisateur froides et instantanés (automatiques) : les blocs d’instantanés froids et les blocs de données utilisateur froids sont déplacés vers le stockage d’objets.
* Toutes les données utilisateur (Toutes) : classe toutes les données comme froides ; déplace immédiatement l’intégralité du volume vers le stockage objet.


link:concept-cloud-tiering.html#volume-tiering-policies["Apprenez-en davantage sur les politiques de hiérarchisation"].



=== À quel moment mes données sont-elles considérées comme froides ?

Étant donné que la hiérarchisation des données s'effectue au niveau des blocs, un bloc de données est considéré comme froid après qu'il n'ait pas été consulté pendant une certaine période, définie par l'attribut minimum-cooling-days de la politique de hiérarchisation.  La plage applicable est de 2 à 63 jours avec ONTAP 9.7 et versions antérieures, ou de 2 à 183 jours à partir d' ONTAP 9.8.



=== Quelle est la période de refroidissement par défaut des données avant leur transfert vers le niveau cloud ?

La période de refroidissement par défaut pour la politique Cold Snapshot est de 2 jours, tandis que la période de refroidissement par défaut pour Cold User Data et les instantanés est de 31 jours.  Le paramètre « jours de refroidissement » n’est pas applicable à la politique de hiérarchisation « Tous les niveaux ».



=== Toutes les données hiérarchisées sont-elles récupérées depuis le stockage objet lors d'une sauvegarde complète ?

Lors d'une sauvegarde complète, toutes les données froides sont lues.  La récupération des données dépend de la politique de hiérarchisation utilisée.  Lorsque les stratégies « Toutes les données utilisateur » et « Données utilisateur froides » sont utilisées, les données froides ne sont pas réécrites dans le niveau de performance.  Lors de l'utilisation de la politique des instantanés à froid, seuls les blocs à froid d'un ancien instantané utilisé pour la sauvegarde seront récupérés.



=== Peut-on choisir une taille de palier par volume ?

Non. Toutefois, vous pouvez choisir les volumes éligibles à la hiérarchisation, le type de données à hiérarchiser et leur période de refroidissement.  Cela se fait en associant une politique de hiérarchisation à ce volume.



=== La politique « Toutes les données utilisateur » est-elle la seule option pour les volumes de protection des données ?

Non. Les volumes de protection des données (DP) peuvent être associés à l'une des trois politiques disponibles.  Le type de politique utilisé sur les volumes source et de destination (DP) détermine l'emplacement d'écriture des données.



=== La réinitialisation de la politique de hiérarchisation d'un volume sur « Aucun » permet-elle de réhydrater les données froides ou empêche-t-elle simplement le déplacement futur des blocs froids vers le cloud ?

Aucune réhydratation n'a lieu lors de la réinitialisation d'une politique de hiérarchisation, mais cela empêchera le déplacement de nouveaux blocs froids vers le niveau cloud.



=== Après avoir transféré des données vers le cloud, puis-je modifier la politique de hiérarchisation ?

Oui. Le comportement après le changement dépend de la nouvelle politique associée.



=== Que dois-je faire si je veux m'assurer que certaines données ne soient pas transférées vers le cloud ?

N’associez pas de politique de hiérarchisation au volume contenant ces données.



=== Où sont stockées les métadonnées des fichiers ?

Les métadonnées d'un volume sont toujours stockées localement, sur le niveau de performance ; elles ne sont jamais transférées vers le cloud.



== Réseau et sécurité

Les questions suivantes concernent les réseaux et la sécurité.



=== Quelles sont les exigences en matière de réseau ?

* Le cluster ONTAP initie une connexion HTTPS sur le port 443 vers votre fournisseur de stockage d'objets.
+
ONTAP lit et écrit des données vers et depuis le stockage d'objets. Le stockage d'objets ne s'initialise jamais, il répond simplement.

* Pour StorageGRID, le cluster ONTAP initie une connexion HTTPS via un port spécifié par l'utilisateur vers StorageGRID (le port est configurable lors de la configuration de la hiérarchisation).
* Un agent a besoin d'une connexion HTTPS sortante sur le port 443 vers vos clusters ONTAP , vers le magasin d'objets et vers le service Cloud Tiering.


Pour plus de détails, voir :

* link:task-tiering-onprem-aws.html["Hiérarchisation des données vers Amazon S3"]
* link:task-tiering-onprem-azure.html["Hiérarchisation des données vers le stockage Blob Azure"]
* link:task-tiering-onprem-gcp.html["Stockage hiérarchisé des données vers Google Cloud Storage"]
* link:task-tiering-onprem-storagegrid.html["Hiérarchisation des données vers StorageGRID"]
* link:task-tiering-onprem-s3-compat.html["Hiérarchisation des données vers le stockage d'objets S3"]




=== Quels outils puis-je utiliser pour la surveillance et le reporting afin de gérer les données froides stockées dans le cloud ?

Outre la hiérarchisation du cloud, https://docs.netapp.com/us-en/active-iq-unified-manager/["Active IQ Unified Manager"^] et https://docs.netapp.com/us-en/active-iq/index.html["conseiller numérique"^] peut être utilisé pour la surveillance et le reporting.



=== Quelles sont les conséquences d'une panne de la connexion réseau avec le fournisseur de cloud ?

En cas de panne de réseau, le niveau de performance local reste en ligne et les données fréquemment utilisées restent accessibles.  Cependant, les blocs déjà déplacés vers le cloud seront inaccessibles et les applications recevront un message d'erreur lorsqu'elles tenteront d'accéder à ces données.  Une fois la connectivité rétablie, toutes les données seront accessibles sans problème.



=== Existe-t-il une recommandation concernant la bande passante réseau ?

La latence de lecture de la technologie de hiérarchisation FabricPool sous-jacente dépend de la connectivité au niveau cloud.  Bien que la hiérarchisation fonctionne sur n'importe quelle bande passante, il est recommandé de placer les LIF inter-clusters sur des ports de 10 Gbit/s pour garantir des performances adéquates.  L'agent ne présente aucune recommandation ni limitation de bande passante.

De plus, vous pouvez limiter la quantité de bande passante réseau utilisée lors du transfert de données inactives du volume vers le stockage objet.  Le paramètre _Débit de transfert maximal_ est disponible lors de la configuration de votre cluster pour la hiérarchisation, puis à partir de la page *Clusters*.



=== Existe-t-il une latence lorsqu'un utilisateur tente d'accéder à des données hiérarchisées ?

Oui. Les niveaux de cloud ne peuvent pas offrir la même latence que le niveau local, car la latence dépend de la connectivité.  Pour estimer la latence et le débit d'un stockage d'objets, Cloud Tiering fournit un test de performance Cloud (basé sur le profileur de stockage d'objets ONTAP ) qui peut être utilisé après la connexion du stockage d'objets et avant la mise en place de la hiérarchisation.



=== Comment mes données sont-elles sécurisées ?

Le chiffrement AES-256-GCM est maintenu à la fois sur les niveaux de performance et de cloud.  Le chiffrement TLS 1.2 est utilisé pour chiffrer les données transitant sur le réseau lors de leur déplacement entre les différents niveaux, et pour chiffrer la communication entre l'agent et le cluster ONTAP ainsi que le magasin d'objets.



=== Ai-je besoin d'un port Ethernet installé et configuré sur mon AFF?

Oui. Une interface LIF inter-cluster doit être configurée sur un port Ethernet, sur chaque nœud d'une paire HA hébergeant des volumes contenant des données que vous prévoyez de transférer vers le cloud.  Pour plus d'informations, consultez la section « Configuration requise » du fournisseur de cloud auprès duquel vous prévoyez de hiérarchiser vos données.



=== Quelles autorisations sont requises ?

* link:task-tiering-onprem-aws.html#set-up-s3-permissions["Pour Amazon, des autorisations sont nécessaires pour gérer le compartiment S3."].
* Pour Azure, aucune autorisation supplémentaire n'est nécessaire en dehors des autorisations que vous devez accorder à la NetApp Console.
* link:task-tiering-onprem-gcp.html#preparing-google-cloud-storage["Pour Google Cloud, les autorisations d'administrateur de stockage sont nécessaires pour un compte de service disposant de clés d'accès au stockage."].
* link:task-tiering-onprem-storagegrid.html#preparing-storagegrid["Pour StorageGRID, les autorisations S3 sont nécessaires."].
* link:task-tiering-onprem-s3-compat.html#preparing-s3-compatible-object-storage["Pour le stockage d'objets compatible S3, les autorisations S3 sont nécessaires."].

