---
settings:
  name: NetApp Cloud Tiering
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: fr-fr,us-en,de-de,es-es,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentation NetApp Cloud Tiering
    url: "/index.html"
  - title: Notes de version
    url: "/whats-new.html"
  - title: Commencer
    entries:
    - title: En savoir plus sur NetApp Cloud Tiering
      url: "/concept-cloud-tiering.html"
    - title: Transférez les données sur site vers le cloud
      entries:
      - title: Niveau vers Amazon S3
        url: "/task-tiering-onprem-aws.html"
      - title: Niveau vers stockage Blob Azure
        url: "/task-tiering-onprem-azure.html"
      - title: Accès à Google Cloud Storage
        url: "/task-tiering-onprem-gcp.html"
      - title: Niveau vers StorageGRID
        url: "/task-tiering-onprem-storagegrid.html"
      - title: Stockage d'objets de niveau S3
        url: "/task-tiering-onprem-s3-compat.html"
    - title: Configurer les licences
      url: "/task-licensing-cloud-tiering.html"
    - title: FAQ
      url: "/faq-cloud-tiering.html"
  - title: Utiliser la NetApp Cloud Tiering
    entries:
    - title: Gérer la hiérarchisation des données
      url: "/task-managing-tiering.html"
    - title: Gérer le stockage d'objets
      url: "/task-managing-object-storage.html"
    - title: Test des performances du cloud
      url: "/task-tiering-test.html"
    - title: Afficher la vue d'ensemble de la hiérarchisation pour tous les clusters
      url: "/task-tiering-onprem-overview.html"
    - title: Surveiller l'état des alertes de hiérarchisation
      url: "/task-monitor-tiering-alerts.html"
  - title: Référence
    entries:
    - title: Classes et régions de stockage Amazon S3 prises en charge
      url: "/reference-aws-support.html"
    - title: Niveaux d'accès et régions Azure pris en charge
      url: "/reference-azure-support.html"
    - title: Classes et régions de stockage Google Cloud prises en charge
      url: "/reference-google-support.html"
  - title: Connaissances et soutien
    entries:
    - title: Inscrivez-vous pour obtenir de l'aide
      url: "/task-support-registration.html"
    - title: Obtenir de l'aide
      url: "/task-get-help.html"
  - title: Mentions légales
    url: "/legal-notices.html"
product-family:
  name: NetApp Data Services
  repo: data-services-family
