---
sidebar: sidebar 
permalink: reference-azure-support.html 
keywords: microsoft azure, azure, hot, access tier, cold, regions, cloud tiering, tier, bluexp 
summary: NetApp Cloud Tiering prend en charge deux niveaux d’accès et la plupart des régions. 
---
= Niveaux et régions d'accès Azure Blob pris en charge pour la hiérarchisation du cloud NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Cloud Tiering prend en charge deux niveaux d’accès et la plupart des régions.



== Niveaux d'accès Azure Blob pris en charge

Lorsque vous configurez la hiérarchisation des données sur Azure à partir de vos systèmes ONTAP locaux, Cloud Tiering utilise automatiquement le niveau d’accès _Hot_ pour vos données inactives.  Cloud Tiering peut appliquer une règle de cycle de vie afin que les données passent du niveau d'accès _Hot_ au niveau d'accès _Cool_ après un certain nombre de jours.

Si vous ne choisissez pas le niveau d'accès _Cool_, les données restent dans le niveau d'accès _Hot_ et aucune règle n'est appliquée.

Lorsque vous configurez une règle de cycle de vie Cloud Tiering, vous ne devez configurer aucune règle de cycle de vie lors de la configuration du conteneur dans votre compte Azure.

https://docs.microsoft.com/en-us/azure/storage/blobs/access-tiers-overview["En savoir plus sur les niveaux d'accès Azure Blob"^] .



== Régions Azure prises en charge

La hiérarchisation du cloud est prise en charge dans toutes les régions Azure, à l’exception de la Chine, où Microsoft Azure est exploité par 21Vianet.
